FROM python:3.9-slim

USER root

COPY requirements.txt /tmp/requirements.txt

RUN pip3 install -r /tmp/requirements.txt

WORKDIR /app

COPY bot.py /app/bot.py
COPY forms.py /app/forms.py
COPY gpt_api_class.py /app/gpt_api_class.py
COPY templates /app/templates
COPY RAG /app/RAG

CMD ["python3", "bot.py"]
