apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ml
  name: open-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-web-ui
  template:
    metadata:
      labels:
        app: open-web-ui
    spec:
      containers:
        - name: open-web-ui
          image: ghcr.io/open-webui/open-webui:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080   
          resources:
            limits:
              cpu: 2
              memory: 1024Mi
          envFrom:
            - configMapRef:
                name: open-web-ui-config
