apiVersion: v1
kind: Service
metadata:
  name: open-web-ui-service
  namespace: ml
spec:
  ports:
    - port: 8080
      name: main
      protocol: TCP
      targetPort: 8080
  selector:
    app: open-web-ui